##################
# Notif to email #
##################
global:
  smtp_smarthost: 'smtp.office365.com:587'
  smtp_from: 'xxx@xxxx.com'
  smtp_auth_username: 'xxx@xxxx.com'
  smtp_auth_password: 'xxxxxx'

route:
  group_by: ['notif']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: devops

  routes:
    - match:
        severity: critical
      receiver: devops

receivers:
- name: 'devops'
  email_configs:
  - to: 'destination@xxxxx.com'

##################
# Notif to slack # 
##################
#receivers:
#  - name: 'devops'
#    slack_configs:
#    - channel: alerts
#      send_resolved: true
#      api_url: https://hooks.slack.com/services/<token-webhook-api-slack>
#      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Notification'
#      text: >-
#        {{ range .Alerts }}
#          *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
#          *Description:* {{ .Annotations.description }}
#          *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
#          *Details:*
#          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
#          {{ end }}
#        {{ end }}

